version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: voice_db
    restart: always
    environment:
      # ä» .env æ–‡ä»¶è¯»å–å˜é‡
      POSTGRES_USER: ${DB_USER}   #è´¦å·
      POSTGRES_PASSWORD: ${DB_PASSWORD}   #å¯†ç 
      POSTGRES_DB: ${DB_NAME}   #æ•°æ®åº“å
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - voice-net

  # å¯¹è±¡å­˜å‚¨æœåŠ¡ MinIO
  minio:
    image: minio/minio:latest
    container_name: voice_minio
    restart: always
    command: server /data --console-address ":9001"  # å¯åŠ¨ MinIO å¹¶å¼€å¯æ§åˆ¶å°
    ports:  # æ˜ å°„ MinIO ç«¯å£
      - "9000:9000"
      - "9001:9001"
    environment:
      # ä» .env æ–‡ä»¶è¯»å–å˜é‡
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    networks:
      - voice-net

  # MinIO åˆå§‹åŒ–è„šæœ¬
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - voice-net
    # ä¹Ÿä½¿ç”¨äº†ç¯å¢ƒå˜é‡
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/voices;
      /usr/bin/mc anonymous set public myminio/voices;
      exit 0;
      "



      backend:
    build: ./backend
    # ... å…¶ä»–é…ç½®
    environment:
      # ğŸ‘‡ è¿™ä¸€è¡Œéå¸¸é‡è¦ï¼
      # å®ƒå‘Šè¯‰ Dockerï¼šè™½ç„¶ .env é‡Œå†™çš„æ˜¯ 5433ï¼ˆç»™æœ¬åœ°å¼€å‘ç”¨çš„ï¼‰ï¼Œ
      # ä½†ä½ åœ¨å®¹å™¨é‡Œè·‘çš„æ—¶å€™ï¼Œè¯·å¼ºåˆ¶ä½¿ç”¨ 5432ï¼
      - DB_PORT=5432
      - DB_HOST=db


networks:
  voice-net:
    driver: bridge

volumes:
  pg_data:
  minio_data:


